services:
  python_00:
    container_name: Krypton
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    volumes:
      - ../:/app
    command: tail -f /dev/null
    working_dir: /app
