services:
  python_03:
    container_name: Pandora
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    volumes:
      - ../:/app
    command: tail -f /dev/null
    working_dir: /app
